# Config for deploybot.app
# Docs https://docs.deploybot.app/config/
# Ordered list of Github Deployment environments
deployments:
- name: development
  on_push: true
- name: staging
- name: production
