# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    env:
      # Setting an environment variable with the value of a configuration variable
      env_var: ${{ vars.ENV_CONTEXT_VAR }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Echo Test
        run: echo '${{ env_var }}'
      - name: Echo vars
        run: echo '${{ toJSON(vars) }}'
      - name: Echo env
        run: echo '${{ toJSON(env) }}'

